### ISSUE TITLE
nppow reference implementation

### ISSUE THREAD

**Issue by excelixwatch** [tevador/nppow#1]
Any implementations you or someone else is working on? Or maybe existing projects trying to implement this algo?

**Comment by tevador** [comment]
This is an experimental proof of work. I'm not aware of any cryptocurrencies planning to implement it at the moment.

The reference implementation of the algorithm is included in this repository. The only potential issue for implementing nppow into an existing cryptocurrency is the need to have additional 16 bytes in the block header.
